import 'dart:convert';

class PlanLimitsConfig {
  static const String jsonString = r'''{
  "free": {
    "price_inr_per_month": 0,
    "billing_model": "flat",
    "max_orgs": 1,
    "max_users": 1,
    "max_customers": 10,
    "max_vendors": 5,
    "max_invoices": 10,
    "max_expenses": 10,
    "max_quotes": 10,
    "max_journal_entries": 10,
    "journal_entry_type": "manual_only",
    "sales_orders_enabled": false,
    "purchase_orders_enabled": false,
    "delivery_challans_enabled": false,
    "credit_notes_enabled": false,
    "banking_enabled": false,
    "inventory_enabled": false,
    "gst_enabled": false,
    "reports_enabled": false,
    "multi_currency_enabled": false,
    "custom_roles_enabled": false,
    "time_tracking_enabled": false,
    "custom_fields_enabled": false,
    "api_access_enabled": false,
    "webhooks_enabled": false,
    "advanced_rbac_enabled": false,
    "audit_logs_enabled": false,
    "dedicated_account_manager": false,
    "workflow_automation_enabled": false,
    "cap_counting_mode": "total_ever_created",
    "cap_reset_period": "lifetime",
    "support": "community",
    "cta_label": "Get started for free",
    "allowed_routes": [
      "/invoices",
      "/payments-received",
      "/customers",
      "/accounting/journals",
      "/dashboard"
    ],
    "route_access_mode": "allowlist",
    "blocked_routes": [
      "/projects",
      "/timesheets",
      "/recurring-invoices",
      "/reports/profit-and-loss",
      "/reports/balance-sheet",
      "/reports/cash-flow",
      "/reports/trial-balance"
    ]
  },
  "standard": {
    "price_inr_per_month": 749,
    "billing_model": "per_org",
    "max_orgs": null,
    "max_users": null,
    "max_customers": 1000,
    "max_vendors": 500,
    "max_invoices": 1000,
    "max_expenses": 1000,
    "max_quotes": 1000,
    "max_journal_entries": 1000,
    "journal_entry_type": "manual_only",
    "sales_orders_enabled": true,
    "purchase_orders_enabled": true,
    "delivery_challans_enabled": true,
    "credit_notes_enabled": true,
    "banking_enabled": true,
    "inventory_enabled": true,
    "gst_enabled": true,
    "reports_enabled": "basic",
    "multi_currency_enabled": false,
    "custom_roles_enabled": false,
    "time_tracking_enabled": false,
    "custom_fields_enabled": false,
    "api_access_enabled": false,
    "webhooks_enabled": false,
    "advanced_rbac_enabled": false,
    "audit_logs_enabled": false,
    "dedicated_account_manager": false,
    "workflow_automation_enabled": false,
    "automated_payment_reminders_enabled": true,
    "cap_counting_mode": "total_ever_created",
    "cap_reset_period": "lifetime",
    "support": "priority",
    "cta_label": "Start 14 Days Trial",
    "trial_days": 14,
    "route_access_mode": "blocklist",
    "blocked_routes": [
      "/projects",
      "/timesheets",
      "/recurring-invoices",
      "/reports/profit-and-loss",
      "/reports/balance-sheet",
      "/reports/cash-flow",
      "/reports/trial-balance"
    ]
  },
  "professional": {
    "price_inr_per_month": 1499,
    "billing_model": "per_org",
    "max_orgs": null,
    "max_users": null,
    "max_customers": null,
    "max_vendors": null,
    "max_invoices": null,
    "max_expenses": null,
    "max_quotes": null,
    "max_journal_entries": null,
    "journal_entry_type": "manual_and_automated",
    "sales_orders_enabled": true,
    "purchase_orders_enabled": true,
    "delivery_challans_enabled": true,
    "credit_notes_enabled": true,
    "banking_enabled": true,
    "inventory_enabled": true,
    "gst_enabled": true,
    "reports_enabled": "advanced",
    "multi_currency_enabled": true,
    "custom_roles_enabled": true,
    "time_tracking_enabled": true,
    "custom_fields_enabled": false,
    "api_access_enabled": false,
    "webhooks_enabled": false,
    "advanced_rbac_enabled": false,
    "audit_logs_enabled": false,
    "dedicated_account_manager": false,
    "workflow_automation_enabled": true,
    "automated_payment_reminders_enabled": true,
    "cap_counting_mode": "total_ever_created",
    "cap_reset_period": "lifetime",
    "support": "24_7_priority",
    "cta_label": "Start 14 Days Trial",
    "trial_days": 14,
    "route_access_mode": "unrestricted",
    "blocked_routes": []
  },
  "enterprise": {
    "price_inr_per_month": 1999,
    "billing_model": "per_org",
    "max_orgs": null,
    "max_users": null,
    "max_customers": null,
    "max_vendors": null,
    "max_invoices": null,
    "max_expenses": null,
    "max_quotes": null,
    "max_journal_entries": null,
    "journal_entry_type": "manual_and_automated",
    "sales_orders_enabled": true,
    "purchase_orders_enabled": true,
    "delivery_challans_enabled": true,
    "credit_notes_enabled": true,
    "banking_enabled": true,
    "inventory_enabled": true,
    "gst_enabled": true,
    "reports_enabled": "advanced",
    "multi_currency_enabled": true,
    "custom_roles_enabled": true,
    "time_tracking_enabled": true,
    "custom_fields_enabled": true,
    "api_access_enabled": true,
    "webhooks_enabled": true,
    "advanced_rbac_enabled": true,
    "audit_logs_enabled": true,
    "dedicated_account_manager": true,
    "workflow_automation_enabled": true,
    "automated_payment_reminders_enabled": true,
    "cap_counting_mode": "total_ever_created",
    "cap_reset_period": "lifetime",
    "support": "dedicated",
    "cta_label": "Start 14 Days Trial",
    "trial_days": 14,
    "route_access_mode": "unrestricted",
    "blocked_routes": []
  },
  "_meta": {
    "trial_maps_to_plan_id": "standard",
    "trial_expired_downgrade_plan_id": "free",
    "subscription_expiry_lock": {
      "applies_to": ["standard", "professional", "enterprise"],
      "trigger": "subscription_status == 'expired'",
      "redirect_route": "/pricing",
      "allowed_routes_while_locked": ["/pricing", "/logout", "/support"],
      "note": "Public/unauthenticated routes remain accessible; this list covers authenticated app routes only."
    },
    "trial_expiry_behavior": {
      "trigger": "subscription_status == 'trial' AND trial_days_remaining <= 0",
      "action": "downgrade_to_plan",
      "downgrade_to": "free",
      "lock_app": false
    },
    "feature_locked_redirect": "/feature-locked?feature=<Feature Name>",
    "billing_cycle": {
      "type": "recurring_monthly",
      "cycle_length_days": 30,
      "applies_to": ["standard", "professional", "enterprise"],
      "renewal_behavior": "auto_charge_on_cycle_end",
      "on_payment_failure_or_no_renewal": {
        "action": "set_status_expired",
        "effect": "triggers subscription_expiry_lock (see above) — full app lock, redirect to /pricing",
        "grace_period_days": 0
      },
      "note": "Free plan has no billing cycle and never expires. Paid plans (including per-org add-ons) must be re-charged every 30 days; failure to renew sets status='expired' which triggers the full app lock in subscription_expiry_lock, NOT the soft trial-downgrade path."
    }
  }
}''';

  static final Map<String, dynamic> data = json.decode(jsonString);
}
