import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_books/core/network/network_client.dart';
import 'package:mobile_books/features/items/data/models/item.dart';
import 'package:mobile_books/features/items/data/models/item_history.dart';
import 'package:mobile_books/features/items/data/models/inventory_movement.dart';

class ItemException implements Exception {
  final String message;
  ItemException(this.message);

  @override
  String toString() => message;
}

class ItemService {
  final NetworkClient _networkClient;

  ItemService(this._networkClient);

  /// Fetches all items belonging to the active tenant/organization
  Future<List<Item>> getItems() async {
    try {
      final response = await _networkClient.get('/items');
      final data = response.data as Map<String, dynamic>;
      final list = data['items'] as List? ?? [];
      return list.map((e) => Item.fromJson(e as Map<String, dynamic>)).toList();
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to fetch items list.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Fetches details of a single item by ID
  Future<Item> getItemById(int id) async {
    try {
      final response = await _networkClient.get('/items/$id');
      final data = response.data as Map<String, dynamic>;
      if (data['item'] != null) {
        return Item.fromJson(data['item'] as Map<String, dynamic>);
      } else {
        throw ItemException('Invalid response structure from server.');
      }
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to fetch item details.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Creates a new product/service item
  Future<Item> createItem(Item item) async {
    try {
      final body = item.toJson();
      body.remove('id'); // ID is generated by backend
      final response = await _networkClient.post('/items', data: body);
      final data = response.data as Map<String, dynamic>;
      if (data['item'] != null) {
        return Item.fromJson(data['item'] as Map<String, dynamic>);
      } else {
        throw ItemException('Invalid response structure from server.');
      }
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to create item.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Updates details of an existing product/service item
  Future<Item> updateItem(int id, Map<String, dynamic> updates) async {
    try {
      final response = await _networkClient.put('/items/$id', data: updates);
      final data = response.data as Map<String, dynamic>;
      if (data['item'] != null) {
        return Item.fromJson(data['item'] as Map<String, dynamic>);
      } else {
        throw ItemException('Invalid response structure from server.');
      }
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to update item.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Hard-deletes a product/service item
  Future<void> deleteItem(int id) async {
    try {
      await _networkClient.delete('/items/$id');
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to delete item.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Fetches audit modification logs/history for an item
  Future<List<ItemHistory>> getItemHistory(int id) async {
    try {
      final response = await _networkClient.get('/items/$id/history');
      final data = response.data as Map<String, dynamic>;
      final list = data['history'] as List? ?? [];
      return list.map((e) => ItemHistory.fromJson(e as Map<String, dynamic>)).toList();
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to fetch item history.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Fetches inventory adjustment movements logs for an item
  Future<List<InventoryMovement>> getItemMovements(int itemId) async {
    try {
      final response = await _networkClient.get('/inventory/items/$itemId/movements');
      final data = response.data as Map<String, dynamic>;
      final list = data['movements'] as List? ?? [];
      return list.map((e) => InventoryMovement.fromJson(e as Map<String, dynamic>)).toList();
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to fetch item inventory movements.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Fetches all inventory adjustment movements logs across all items
  Future<List<InventoryMovement>> getInventoryMovements() async {
    try {
      final response = await _networkClient.get('/inventory/movements');
      final data = response.data as Map<String, dynamic>;
      final list = data['movements'] as List? ?? [];
      return list.map((e) => InventoryMovement.fromJson(e as Map<String, dynamic>)).toList();
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to fetch inventory movements.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Creates a manual stock adjustment movement for an item (e.g. stock_in/stock_out/adjustment)
  Future<Map<String, dynamic>> createInventoryMovement(Map<String, dynamic> body) async {
    try {
      final response = await _networkClient.post('/inventory/movements', data: body);
      final data = response.data as Map<String, dynamic>;
      return data;
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to create inventory adjustment.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }

  /// Fetches contact vendors list from backend
  Future<List<Map<String, dynamic>>> getVendors() async {
    try {
      final response = await _networkClient.get('/contacts');
      final data = response.data as Map<String, dynamic>;
      final list = data['contacts'] as List? ?? [];
      return list
          .map((e) => e as Map<String, dynamic>)
          .where((e) => e['type'] == 'vendor' || e['type'] == 'Vendor')
          .toList();
    } on DioException catch (e) {
      final message = e.response?.data?['message'] as String? ?? 'Failed to fetch vendors.';
      throw ItemException(message);
    } catch (e) {
      throw ItemException(e.toString());
    }
  }
}

final itemServiceProvider = Provider<ItemService>((ref) {
  final networkClient = ref.watch(networkClientProvider);
  return ItemService(networkClient);
});
